### ISSUE TITLE
Add 'source_text_notes' on FamilyRelationship table to the ES model under 'family_members'

### ISSUE THREAD

**Issue by junjun-zhang** [kids-first/kf-es-model#37]
This field (source_text_notes) was added in dataservice 1.3.0 (https://github.com/kids-first/kf-api-dataservice/pull/414), if it's needed to be searched, it will need to be added to ES model.

**Comment by allisonheath** [comment]
I'm not sure we want it searchable just yet - we loaded them into the dataservice so it's easier to take a look to understand what the use cases around it are rather than look it back up in the source files. But I think there were some good points on the directionality of these comments that might make it confusing to the user at this time.
